### ISSUE TITLE
Please correct and complete the documentation

### ISSUE THREAD

**Issue by nise** [cescobedo/moodle-local_upgradedb#2]
The git command only works for the owner of this repository. 

Instead try: ` git clone https://github.com/cescobedo/moodle-local_upgradedb` inside the moodle/local
and: `cd moodle-local_upgradedb && mv moodle-local_upgradedb/ upgradedb`
Then I changed the ownership to www-data: ` sudo chown -R www-data upgradedb`

Unfortunately I was not able to find the entry point from where I could start to upgrade my tables. 

Could you help?

**Comment by nise** [comment]
Oh, I got it. One need to go to Site Administration > Notifications and upgrade the plugin befor being able to use it.

After completing the always strange moodle installation process the plugin appears under 'Development' in the Site Administration.

**Comment by cescobedo** [comment]
Hi Nise, 

I'm sorry I saw your issue late. Thanks for using the plugin.
