### ISSUE TITLE
Wrong help link

### ISSUE THREAD

**Issue by nise** [cescobedo/moodle-local_upgradedb#3]
I got the Error: Incorrect table "videodatabase_annotations" definition; there can be only one auto column and it must be defined as a key" including a link to a non-existing page: https://docs.moodle.org/33/en/error/moodle/ddsequenceerror

**Comment by nise** [comment]
Instead of this confusing error message you could simply note that there should not be more then one field where the attribute SEQUENCE is set TRUE.

**Comment by cescobedo** [comment]
Hi Nise,

This error is part of Moodle Core and it's not managed in the Plugin. But, I will check what I can do.

Thanks for your comment.
